package model;
// Generated 19 mars 2022, 13:13:22 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "cantine_universitaire")
public class Administrateur implements java.io.Serializable {

	private Integer idAdmin;
	private String login;
	private String motDePasse;

	public Administrateur() {
	}

	public Administrateur(String login, String motDePasse) {
		this.login = login;
		this.motDePasse = motDePasse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_admin", unique = true, nullable = false)
	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "login", nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "mot_de_passe", nullable = false, length = 50)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

}
