package model;
// Generated 19 mars 2022, 13:13:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "cantine_universitaire")
public class Commande implements java.io.Serializable {

	private Integer idCommande;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public Commande() {
	}

	public Commande(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_commande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
