package model;
// Generated 19 mars 2022, 13:13:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "cantine_universitaire")
public class Menu implements java.io.Serializable {

	private Integer idMenu;
	private Set<Date> dates = new HashSet<Date>(0);

	public Menu() {
	}

	public Menu(Set<Date> dates) {
		this.dates = dates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_menu", unique = true, nullable = false)
	public Integer getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(Integer idMenu) {
		this.idMenu = idMenu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Date> getDates() {
		return this.dates;
	}

	public void setDates(Set<Date> dates) {
		this.dates = dates;
	}

}
