package model;
// Generated 19 mars 2022, 13:13:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockBoisson generated by hbm2java
 */
@Entity
@Table(name = "stock_boisson", catalog = "cantine_universitaire")
public class StockBoisson implements java.io.Serializable {

	private Integer idStockboisson;
	private int quantite;
	private Set<Boisson> boissons = new HashSet<Boisson>(0);

	public StockBoisson() {
	}

	public StockBoisson(int quantite) {
		this.quantite = quantite;
	}

	public StockBoisson(int quantite, Set<Boisson> boissons) {
		this.quantite = quantite;
		this.boissons = boissons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_stockboisson", unique = true, nullable = false)
	public Integer getIdStockboisson() {
		return this.idStockboisson;
	}

	public void setIdStockboisson(Integer idStockboisson) {
		this.idStockboisson = idStockboisson;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockBoisson")
	public Set<Boisson> getBoissons() {
		return this.boissons;
	}

	public void setBoissons(Set<Boisson> boissons) {
		this.boissons = boissons;
	}

}
