package model;
// Generated 19 mars 2022, 13:13:22 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockPlat generated by hbm2java
 */
@Entity
@Table(name = "stock_plat", catalog = "cantine_universitaire")
public class StockPlat implements java.io.Serializable {

	private Integer idStockplat;
	private int quantite;
	private Set<Plat> plats = new HashSet<Plat>(0);

	public StockPlat() {
	}

	public StockPlat(int quantite) {
		this.quantite = quantite;
	}

	public StockPlat(int quantite, Set<Plat> plats) {
		this.quantite = quantite;
		this.plats = plats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_stockplat", unique = true, nullable = false)
	public Integer getIdStockplat() {
		return this.idStockplat;
	}

	public void setIdStockplat(Integer idStockplat) {
		this.idStockplat = idStockplat;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockPlat")
	public Set<Plat> getPlats() {
		return this.plats;
	}

	public void setPlats(Set<Plat> plats) {
		this.plats = plats;
	}

}
