package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class acceuilController {

	// Event Listener on Button.onAction
	@FXML
	public void ouvrircomm(ActionEvent event) {
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/commande.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}

	}
	// Event Listener on Button.onAction
	@FXML
	public void ouvrirstock(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/gestionstock.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}

	}
	// Event Listener on Button.onAction
	@FXML
	public void ouvrirEdonnee(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/Edonnees.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}

	}
	// Event Listener on Button.onAction
	@FXML
	public void ouvrirbilan(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/bilan.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}

	}
}
