package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class bilanController {

	// Event Listener on Button.onAction
	@FXML
	public void ouvrirbilanplats(ActionEvent event) {
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/bilanplats.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void ouvrirbilanbois(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/bilanbois.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void retouracceuil(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent root1 =FXMLLoader.load(getClass().getResource("/application/acceuil.fxml"));
			Scene scene= new Scene(root1);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
}
