package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class EdonneesController {

	// Event Listener on Button.onAction
	@FXML
	public void affichmenu(ActionEvent event) {
		// TODO Autogeneratedtry 
		try{
		Parent root=FXMLLoader.load(getClass().getResource("/application/mes tickets.fxml"));
		Scene scene= new Scene(root);
		Stage stage = new Stage();
		stage.setScene(scene);
		stage.show();
		
		
	} catch (Exception e) {
		// TODO: handle exception
	}
	}
	// Event Listener on Button.onAction
	@FXML
	public void affplats(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void afficbois(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void affichacceuil(ActionEvent event) {
		// TODO Autogenerated
	}
}
